script: bundle install; bundle exec rspec spec
language: ruby
rvm:
  - 2.1.0
notifications:
  webhooks:
    urls:
      - http://travis-harness.ngrok.com/
    on_success: always
    on_failure: always
    on_start: true
before_install:
  - gem install bundler
cache: bundler
env:
  global:
